### ISSUE TITLE
Change ownership of "slider" extension

### ISSUE THREAD

**Issue by twiro** [symphonists/symphony-extensions-network#1]
> > _a "how-to-transfer-ownership-on-symphonyextensions.com" guide as well as the possibility to file a new issue to request the change if I can't do it myself would be a pretty good start!_
> 
> _Good point!_

Here we go - first issue on this repo :)

Ownership of the "slider" extension has been transfered to my github-account today:
- http://symphonyextensions.com/extensions/slider/
- https://github.com/twiro/slider

It would be great to reflect that change on symphonyextensions.com.

It would be even greater to include a first "FAQ" in the readme that would give me instructions how a change of ownership on symphonyextensions.com works and what i should best do to accomplish it.

**Comment by andrewminton** [comment]
Forgot this repo existed! such a nice feature! glad to see it's continuing with you @twrio :)

**Comment by nitriques** [comment]
@andrewminton 

> Forgot this repo existed

It never did! We created yesterday!

@twiro I've updated the extension, should display are yours as soon as the cache expires.

**Comment by andrewminton** [comment]
Haha. Why do I get the feeling I've seen it before.. like years ago? I'm pretty sure I have something very similar install on a 2.0.7 install for some bizzare reason... it was in the era of Rowan and the Colour picker extension days.

**Comment by twiro** [comment]
> > Forgot this repo existed! such a nice feature! glad to see it's continuing with you @twrio :)
> 
> It never did! We created yesterday!

I think Andrew is talking about the "**[slider](https://github.com/twiro/slider)**" repo - and Nicolas about the "**[symphony extension network](https://github.com/symphonists/symphony-extensions-network)**" ;) Right?

Regarding the slider extension - I have it running on an older website (2.3) that I'm about to update these days - as the extension has been abandoned for quite some time I thought it would be a great opportunity to take care of it, update and improve it and learn a little more about extension development without having to start from scratch (haven't developed an own extension yet).

I already changed the slider plugin (from jquery-ui to nouislider), rewrote the readme and improved 2.3-compatibility but as I'm rather slow due to missing extension-development-experience it might take some more time before I'll submit an updated version to github (and symphonyextensions.com!).

I'm planning to make the current version support Symphony 2.3 to 2.6.X and then maybe work on a bigger update which offers a little more flexibilty regarding the supported slider settings. It's pretty limited right now.

> @twiro I've updated the extension, should display are yours as soon as the cache expires.

Thank you very much Nicolas! My first listing on symphonyextensions.com :)

http://symphonyextensions.com/extensions/slider/

"Reflected Upload Field" will follow...

**Comment by nitriques** [comment]
> I think Andrew is talking about the "slider" repo - and Nicolas about the "symphony extension network" ;) Right?

Ah that may be the case!!!

> "Reflected Upload Field" will follow...

Awesome!
