### ISSUE TITLE
Extension Transfer: Text Box Field

### ISSUE THREAD

**Issue by twiro** [symphonists/symphony-extensions-network#10]
On behalf of a healthy extension ecosystem I would like to propose an extension transfer of the Text Box Field extension:
- **Text Box Field** is currently [actively maintained](https://github.com/symphonists/textboxfield/commits/master) by the symphonists and 20 commits ahead of [Rowans repo](https://github.com/psychoticmeow/textboxfield) that hasn't been updated in 3 years.
- **Symphonyextensions.com** is still listing [Rowans repo](http://symphonyextensions.com/extensions/textboxfield/) as the official extension resource.
- **Multilingual Field** also lists [Rowans repo](https://github.com/DeuxHuitHuit/multilingual_field#2-installation) as a dependency.

I think this should be changed by...
1. ...transferring ownership of the extension to either the symphonists account or _(even better)_ to someone who is willing to personally take care of the extension.
2. ...fixing the entry on symphonyextensions.com and linking to the new "official" repo (will also solve the problem for multilingual field).

@nitriques , @psychoticmeow, @brendo

**Comment by nitriques** [comment]
http://symphonyextensions.com/extensions/textboxfield/

https://github.com/DeuxHuitHuit/multilingual_field/blob/master/extension.meta.xml#L28

Are we good now ? :+1:
