### ISSUE TITLE
Extension Transfer: Member Last Visit

### ISSUE THREAD

**Issue by twiro** [symphonists/symphony-extensions-network#20]
Hey Nicolas,

I just adopted [Member Last Visit](https://github.com/twiro/member_last_visit) from [Mark Lewis](https://github.com/lewiswharf), drafted a [new release](https://github.com/twiro/member_last_visit/tree/1.0.6) for Symphony 2.4-2.6 compatibility and will now start working on an update for Symphony 2.7.

Could you please change ownership of the extension on [symphonyextensions.com](http://symphonyextensions.com/extensions/member_last_visit/) – Thank you very much!

**Comment by nitriques** [comment]
Should be done! Comment if it's not ok !
