### ISSUE TITLE
Extension Adoption: klaftertief/page_prototypes

### ISSUE THREAD

**Issue by klaftertief** [symphonists/symphony-extensions-network#23]
@twiro contacted me to transfer one of my old extensions to his account. He also suggested to transfer other extensions to the symphonists organisation. I'm happy to do that as I stopped using Symphony a couple of years ago. I was not able to transfer this extension directly, so here is the PR :-)

https://github.com/klaftertief/page_prototypes/

**Comment by klaftertief** [comment]
I moved the extension to https://github.com/klaftertief-symphony, @nitriques is invited.

**Comment by nitriques** [comment]
It's been transferred. thanks.
