### ISSUE TITLE
Extension Transfer: Geocoding Field

### ISSUE THREAD

**Issue by twiro** [symphonists/symphony-extensions-network#26]
Hey Nicolas,

I've adopted the extension [geocodingfield](https://github.com/twiro/geocodingfield) from @klaftertief, so it would be cool if you could change things accordingly on [sympohnyextensions.com](http://symphonyextensions.com/extensions/geocodingfield/).

Extension-Updates will follow & big thanks to Jonas for originally crafting this!

**Comment by twiro** [comment]
Thanks @nitriques !

**Comment by nitriques** [comment]
👍
