### ISSUE TITLE
Latest release of "Output Field" not showing up on symphonyextensions.com

### ISSUE THREAD

**Issue by twiro** [symphonists/symphony-extensions-network#27]
It's been 6 days since I published the latest [release 2.1.0](https://github.com/symphonists/output_field/releases/tag/2.1.0) of Output Field, but it's still not showing up on [symphonyextensions.com](http://symphonyextensions.com/extensions/output_field/). Could you have a look @nitriques?

**Comment by nitriques** [comment]
I've fixed it in [those two commits](https://github.com/symphonists/output_field/compare/a8a5a2cb4de26f4485d3dd7dd071bdaa595f9016~2...a8a5a2cb4de26f4485d3dd7dd071bdaa595f9016) I took me a lot of time to figure it out, but was a wrong namespace. Sorry !

**Comment by twiro** [comment]
I have to say sorry for including the wrong namespace – thanks for fixing it!

**Comment by nitriques** [comment]
Np!
