### ISSUE TITLE
Change ownership of »Language: German« extension

### ISSUE THREAD

**Issue by animaux** [symphonists/symphony-extensions-network#3]
The [lang_german](http://symphonyextensions.com/extensions/lang_german/) extension has been moved to a [repo in my github account](https://github.com/animaux/lang_german). It redirects properly on github but should have the proper owner in the first place. If I log into the extensions-site via github I don’t see any repositories I could add.

**Comment by nitriques** [comment]
[There you go!](http://symphonyextensions.com/extensions/lang_german/)

Thanks!

**Comment by nitriques** [comment]
Would you mind updating the compat info ? Thanks!

**Comment by animaux** [comment]
Cheers! Info should be ok like it is, I think.

**Comment by animaux** [comment]
Actually there’s a bug with the version display on the extensions site. https://github.com/symphonists/symphony-extensions-network/issues/4 @nilshoerrmann says it’s been like this for quite some time.

**Comment by nitriques** [comment]
> The simplest thing a developer can do is add the max attribute.

:) that's what needs to be done, sadly.
