### ISSUE TITLE
Organization extensions can not be removed

### ISSUE THREAD

**Issue by michael-e** [symphonists/symphony-extensions-network#7]
Extensions belonging to an organization can be added but not removed. This is a show-stopper for certain cleanup efforts of the community.

**Comment by nitriques** [comment]
Yeah right now, this would require a lot of efforts. What I meant was that one should create a issue on this site telling be what do delete. Sadly, this will stay a manual process.

**Comment by michael-e** [comment]
Ah, I see. Will close this and open a new issue.

**Comment by nitriques** [comment]
:+1:
